### ISSUE TITLE
placed coolers dont have dyed colour

### ISSUE THREAD

**Issue by lunchboxxx19** [gudenau/Coolers#1]
with version 2.0.0.2 when a dyed cooler is placed in world it doesnt have the colour it is dyed as just the standard white colour

**Comment by gudenau** [comment]
Does it show the color in the inventory?
Does it show when you pick it up?
May I have a world with this problem?

**Comment by lunchboxxx19** [comment]
sorry should have included that information.
the cooler will occasionally show its dyed colour when placed in the inventory
if i place it down then pick it up it loses its colour and doesnt even say that its dyed
also the clear one will revert to a standard cooler when broken as well as lose its dye colour

what files will you need for a world to work? ive never shared one before

**Comment by gudenau** [comment]
The entire directory inside of the world, saves/worldName if I recall.

**Comment by lunchboxxx19** [comment]
http://www.mediafire.com/file/0rsc5536x3m71p4/test_world.zip

i think that should do it

**Comment by gudenau** [comment]
Got around to checking the world, there does not appear to be an inventory for the player and I do not see any coolers in the world.

**Comment by lunchboxxx19** [comment]
ok try this world - http://www.mediafire.com/file/ee6eci8izvxtaye/Test+world.zip

**Comment by gudenau** [comment]
This does not show up in a dev environment, but it does outside. How fun. :-/

**Comment by gudenau** [comment]
@lunchboxxx19 check the current version, as soon as it is approved.

**Comment by lunchboxxx19** [comment]
hey the current version seems to have fixed the dye colour not staying but now it doesnt completely feed the player leaving about three hams empty

**Comment by gudenau** [comment]
That's intended to prevent them from being overpowered, with the fast
healing that was added you could become hard to kill.
